# Generated by Django 3.0.5 on 2020-04-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor_ip", models.CharField(max_length=15)),
                ("time_visited", models.DateTimeField(verbose_name="date visited")),
            ],
        ),
    ]
