# Generated by Django 3.0.5 on 2020-04-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zweedendev", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Visitors", new_name="Visitor",),
    ]
