# Generated by Django 3.0.5 on 2020-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zweedendev", "0002_auto_20200402_0337"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="visitor_city_region",
            field=models.CharField(default="Unknown, Unknown", max_length=255),
        ),
    ]
