# Generated by Django 3.0.5 on 2020-04-04 01:42
import ipaddress
import requests
from zweedendev.models import Visitor
from django.db import migrations


def resolve_location(apps, schema_editor):
    unknown_location_visitors = Visitor.objects.filter(
        visitor_city_region="Unknown, Unknown"
    )
    for visitor in unknown_location_visitors:
        ip = visitor.visitor_ip
        is_private = ipaddress.ip_address(ip).is_private
        if is_private:
            continue
        try:
            r = requests.get(
                f"https://ipapi.co/{ip}/json/",
                headers={
                    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"
                },
            )
            city_region = f'{r.json().get("city", "Unknown")}, {r.json().get("region", "Unknown")}'
            visitor.visitor_city_region = city_region
            visitor.save()
        except:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("zweedendev", "0004_auto_20200403_2135"),
    ]

    operations = [
        migrations.RunPython(resolve_location),
    ]
