# Generated by Django 3.0.5 on 2020-04-08 17:19
import ipaddress
from zweedendev.models import Visitor
from django.db import migrations


def resolve_privacy(apps, schema_editor):
    visitors = Visitor.objects.all()
    for visitor in visitors:
        ip = visitor.visitor_ip
        is_private = ipaddress.ip_address(ip).is_private
        visitor.is_private = is_private
        visitor.save()


def resolve_number_times_visited(apps, schema_editor):
    visitors = Visitor.objects.all()
    for visitor in visitors:
        visitor.times_visited = 1
        visitor.save()


class Migration(migrations.Migration):

    dependencies = [
        ("zweedendev", "0008_auto_20200408_1316"),
    ]

    operations = [
        migrations.RunPython(resolve_privacy),
        migrations.RunPython(resolve_number_times_visited),
    ]
